# Add a service for each of the two AI 

services:
    main:
        build: ./main
        ports:
          - "82:5000"
    aitwo:
        build: ./AITwo
        expose: 
          - "5000"

    aione: 
        build: ./AIOne
        expose: 
          - "5000"

